### ISSUE TITLE
Install the Drupal in docker stuck on 98%

### ISSUE THREAD

**Issue by aryaroudi** [apigee/apigee-devportal-kickstart-drupal#347]
**Describe the bug**
I set up my environment with Lando and tried on 2 different MacBook Pro laptops and the installation stuck on 98% and not going further.
**To Reproduce**
Do the `lando start`
Open the environment in the browser (It will redirect you to Install page)
Enter the database details

**Expected behavior**
There should be an error to show why it stuck there

**Screenshots**
![image](https://user-images.githubusercontent.com/43990136/78275054-66ee2b80-7511-11ea-9859-1fc4c5f2e137.png)

**Additional context**
If I install the drupal bu `drush` it works fine btw

**Version Info**
Drupal: 8.8
Lando: 3.0.0-rrc.2
MySql: 8.0.19

**Comment by cnovak** [comment]
@aryaroudi could you share your lando config with us to help validate?

**Comment by shadcn** [comment]
@aryaroudi did you figure this out? 

I just tested with the following `.lando.yml` config and it worked. 

```yml
name: kickstart

recipe: drupal8

config:
  webroot: web
  php: 7.3
  database: mariadb
```

If you could post your lando config, we can test it.

**Comment by aryaroudi** [comment]
hey @cnovak yes sure:

```
name: d8-composer-verify
recipe: drupal8
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
config:
  drush: "*"
  webroot: web
  database: 'mysql:8.0.19'
  config:
    database: config_lando/my-custom.cnf
```
not yet, I'm just continued to install it by `drush si` and that way it works, anyway I guess it won't be a concern for me as we need to put the whole process in a CI/CD pipeline and we need to install it by CLI but just shared it in case someone faces the same issue in the web console
